use crate::bespoke_event_handling::apply_bespoke_event_handling;
use crate::bespoke_event_handling::maybe_emit_hook_prompt_item_completed;
use crate::command_exec::CommandExecManager;
use crate::command_exec::StartCommandExecParams;
use crate::config_manager::ConfigManager;
use crate::error_code::INPUT_TOO_LARGE_ERROR_CODE;
use crate::error_code::invalid_params;
use crate::models::supported_models;
use crate::outgoing_message::ConnectionId;
use crate::outgoing_message::ConnectionRequestId;
use crate::outgoing_message::OutgoingMessageSender;
use crate::outgoing_message::RequestContext;
use crate::outgoing_message::ThreadScopedOutgoingMessageSender;
use crate::skills_watcher::SkillsWatcher;
use crate::thread_status::ThreadWatchManager;
use crate::thread_status::resolve_thread_status;
use anecdoct_analytics::AnalyticsEventsClient;
use anecdoct_analytics::AnalyticsJsonRpcError;
use anecdoct_analytics::InputError;
use anecdoct_analytics::TurnSteerRequestError;
use anecdoct_app_server_protocol::Account;
use anecdoct_app_server_protocol::AccountLoginCompletedNotification;
use anecdoct_app_server_protocol::AccountUpdatedNotification;
use anecdoct_app_server_protocol::AddCreditsNudgeCreditType;
use anecdoct_app_server_protocol::AddCreditsNudgeEmailStatus;
use anecdoct_app_server_protocol::AnecdoctErrorInfo;
use anecdoct_app_server_protocol::AppInfo;
use anecdoct_app_server_protocol::AppListUpdatedNotification;
use anecdoct_app_server_protocol::AppSummary;
use anecdoct_app_server_protocol::AppsListParams;
use anecdoct_app_server_protocol::AppsListResponse;
use anecdoct_app_server_protocol::AskForApproval;
use anecdoct_app_server_protocol::AuthMode;
use anecdoct_app_server_protocol::CancelLoginAccountParams;
use anecdoct_app_server_protocol::CancelLoginAccountResponse;
use anecdoct_app_server_protocol::CancelLoginAccountStatus;
use anecdoct_app_server_protocol::ClientInfo;
use anecdoct_app_server_protocol::ClientRequest;
use anecdoct_app_server_protocol::ClientResponsePayload;
use anecdoct_app_server_protocol::CollaborationModeListParams;
use anecdoct_app_server_protocol::CollaborationModeListResponse;
use anecdoct_app_server_protocol::CommandExecParams;
use anecdoct_app_server_protocol::CommandExecResizeParams;
use anecdoct_app_server_protocol::CommandExecTerminateParams;
use anecdoct_app_server_protocol::CommandExecWriteParams;
use anecdoct_app_server_protocol::ConfigWarningNotification;
use anecdoct_app_server_protocol::ConversationGitInfo;
use anecdoct_app_server_protocol::ConversationSummary;
use anecdoct_app_server_protocol::DeprecationNoticeNotification;
use anecdoct_app_server_protocol::DynamicToolSpec as ApiDynamicToolSpec;
use anecdoct_app_server_protocol::EnvironmentAddParams;
use anecdoct_app_server_protocol::EnvironmentAddResponse;
use anecdoct_app_server_protocol::ExperimentalFeature as ApiExperimentalFeature;
use anecdoct_app_server_protocol::ExperimentalFeatureListParams;
use anecdoct_app_server_protocol::ExperimentalFeatureListResponse;
use anecdoct_app_server_protocol::ExperimentalFeatureStage as ApiExperimentalFeatureStage;
use anecdoct_app_server_protocol::FeedbackUploadParams;
use anecdoct_app_server_protocol::FeedbackUploadResponse;
use anecdoct_app_server_protocol::GetAccountParams;
use anecdoct_app_server_protocol::GetAccountRateLimitsResponse;
use anecdoct_app_server_protocol::GetAccountResponse;
use anecdoct_app_server_protocol::GetAuthStatusParams;
use anecdoct_app_server_protocol::GetAuthStatusResponse;
use anecdoct_app_server_protocol::GetConversationSummaryParams;
use anecdoct_app_server_protocol::GetConversationSummaryResponse;
use anecdoct_app_server_protocol::GitDiffToRemoteParams;
use anecdoct_app_server_protocol::GitDiffToRemoteResponse;
use anecdoct_app_server_protocol::GitInfo as ApiGitInfo;
use anecdoct_app_server_protocol::HookMetadata;
use anecdoct_app_server_protocol::HooksListParams;
use anecdoct_app_server_protocol::HooksListResponse;
use anecdoct_app_server_protocol::InitializeParams;
use anecdoct_app_server_protocol::InitializeResponse;
use anecdoct_app_server_protocol::JSONRPCErrorError;
use anecdoct_app_server_protocol::ListMcpServerStatusParams;
use anecdoct_app_server_protocol::ListMcpServerStatusResponse;
use anecdoct_app_server_protocol::LoginAccountParams;
use anecdoct_app_server_protocol::LoginAccountResponse;
use anecdoct_app_server_protocol::LoginApiKeyParams;
use anecdoct_app_server_protocol::LogoutAccountResponse;
use anecdoct_app_server_protocol::MarketplaceAddParams;
use anecdoct_app_server_protocol::MarketplaceAddResponse;
use anecdoct_app_server_protocol::MarketplaceInterface;
use anecdoct_app_server_protocol::MarketplaceRemoveParams;
use anecdoct_app_server_protocol::MarketplaceRemoveResponse;
use anecdoct_app_server_protocol::MarketplaceUpgradeErrorInfo;
use anecdoct_app_server_protocol::MarketplaceUpgradeParams;
use anecdoct_app_server_protocol::MarketplaceUpgradeResponse;
use anecdoct_app_server_protocol::McpResourceReadParams;
use anecdoct_app_server_protocol::McpResourceReadResponse;
use anecdoct_app_server_protocol::McpServerOauthLoginCompletedNotification;
use anecdoct_app_server_protocol::McpServerOauthLoginParams;
use anecdoct_app_server_protocol::McpServerOauthLoginResponse;
use anecdoct_app_server_protocol::McpServerRefreshResponse;
use anecdoct_app_server_protocol::McpServerStatus;
use anecdoct_app_server_protocol::McpServerStatusDetail;
use anecdoct_app_server_protocol::McpServerToolCallParams;
use anecdoct_app_server_protocol::McpServerToolCallResponse;
use anecdoct_app_server_protocol::MemoryResetResponse;
use anecdoct_app_server_protocol::MockExperimentalMethodParams;
use anecdoct_app_server_protocol::MockExperimentalMethodResponse;
use anecdoct_app_server_protocol::ModelListParams;
use anecdoct_app_server_protocol::ModelListResponse;
use anecdoct_app_server_protocol::PermissionProfileSelectionParams;
use anecdoct_app_server_protocol::PluginDetail;
use anecdoct_app_server_protocol::PluginInstallParams;
use anecdoct_app_server_protocol::PluginInstallResponse;
use anecdoct_app_server_protocol::PluginInterface;
use anecdoct_app_server_protocol::PluginListMarketplaceKind;
use anecdoct_app_server_protocol::PluginListParams;
use anecdoct_app_server_protocol::PluginListResponse;
use anecdoct_app_server_protocol::PluginMarketplaceEntry;
use anecdoct_app_server_protocol::PluginReadParams;
use anecdoct_app_server_protocol::PluginReadResponse;
use anecdoct_app_server_protocol::PluginShareCheckoutParams;
use anecdoct_app_server_protocol::PluginShareCheckoutResponse;
use anecdoct_app_server_protocol::PluginShareContext;
use anecdoct_app_server_protocol::PluginShareDeleteParams;
use anecdoct_app_server_protocol::PluginShareDeleteResponse;
use anecdoct_app_server_protocol::PluginShareDiscoverability;
use anecdoct_app_server_protocol::PluginShareListItem;
use anecdoct_app_server_protocol::PluginShareListParams;
use anecdoct_app_server_protocol::PluginShareListResponse;
use anecdoct_app_server_protocol::PluginSharePrincipal;
use anecdoct_app_server_protocol::PluginSharePrincipalType;
use anecdoct_app_server_protocol::PluginShareSaveParams;
use anecdoct_app_server_protocol::PluginShareSaveResponse;
use anecdoct_app_server_protocol::PluginShareTarget;
use anecdoct_app_server_protocol::PluginShareUpdateDiscoverability;
use anecdoct_app_server_protocol::PluginShareUpdateTargetsParams;
use anecdoct_app_server_protocol::PluginShareUpdateTargetsResponse;
use anecdoct_app_server_protocol::PluginSkillReadParams;
use anecdoct_app_server_protocol::PluginSkillReadResponse;
use anecdoct_app_server_protocol::PluginSource;
use anecdoct_app_server_protocol::PluginSummary;
use anecdoct_app_server_protocol::PluginUninstallParams;
use anecdoct_app_server_protocol::PluginUninstallResponse;
use anecdoct_app_server_protocol::RequestId;
use anecdoct_app_server_protocol::ReviewDelivery as ApiReviewDelivery;
use anecdoct_app_server_protocol::ReviewStartParams;
use anecdoct_app_server_protocol::ReviewStartResponse;
use anecdoct_app_server_protocol::ReviewTarget as ApiReviewTarget;
use anecdoct_app_server_protocol::SandboxMode;
use anecdoct_app_server_protocol::SendAddCreditsNudgeEmailParams;
use anecdoct_app_server_protocol::SendAddCreditsNudgeEmailResponse;
use anecdoct_app_server_protocol::ServerNotification;
use anecdoct_app_server_protocol::ServerRequestResolvedNotification;
use anecdoct_app_server_protocol::SkillSummary;
use anecdoct_app_server_protocol::SkillsConfigWriteParams;
use anecdoct_app_server_protocol::SkillsConfigWriteResponse;
use anecdoct_app_server_protocol::SkillsListParams;
use anecdoct_app_server_protocol::SkillsListResponse;
use anecdoct_app_server_protocol::SortDirection;
use anecdoct_app_server_protocol::Thread;
use anecdoct_app_server_protocol::ThreadApproveGuardianDeniedActionParams;
use anecdoct_app_server_protocol::ThreadApproveGuardianDeniedActionResponse;
use anecdoct_app_server_protocol::ThreadArchiveParams;
use anecdoct_app_server_protocol::ThreadArchiveResponse;
use anecdoct_app_server_protocol::ThreadArchivedNotification;
use anecdoct_app_server_protocol::ThreadBackgroundTerminalsCleanParams;
use anecdoct_app_server_protocol::ThreadBackgroundTerminalsCleanResponse;
use anecdoct_app_server_protocol::ThreadClosedNotification;
use anecdoct_app_server_protocol::ThreadCompactStartParams;
use anecdoct_app_server_protocol::ThreadCompactStartResponse;
use anecdoct_app_server_protocol::ThreadDecrementElicitationParams;
use anecdoct_app_server_protocol::ThreadDecrementElicitationResponse;
use anecdoct_app_server_protocol::ThreadForkParams;
use anecdoct_app_server_protocol::ThreadForkResponse;
use anecdoct_app_server_protocol::ThreadGoal;
use anecdoct_app_server_protocol::ThreadGoalClearParams;
use anecdoct_app_server_protocol::ThreadGoalClearResponse;
use anecdoct_app_server_protocol::ThreadGoalClearedNotification;
use anecdoct_app_server_protocol::ThreadGoalGetParams;
use anecdoct_app_server_protocol::ThreadGoalGetResponse;
use anecdoct_app_server_protocol::ThreadGoalSetParams;
use anecdoct_app_server_protocol::ThreadGoalSetResponse;
use anecdoct_app_server_protocol::ThreadGoalStatus;
use anecdoct_app_server_protocol::ThreadGoalUpdatedNotification;
use anecdoct_app_server_protocol::ThreadHistoryBuilder;
use anecdoct_app_server_protocol::ThreadIncrementElicitationParams;
use anecdoct_app_server_protocol::ThreadIncrementElicitationResponse;
use anecdoct_app_server_protocol::ThreadInjectItemsParams;
use anecdoct_app_server_protocol::ThreadInjectItemsResponse;
use anecdoct_app_server_protocol::ThreadItem;
use anecdoct_app_server_protocol::ThreadListCwdFilter;
use anecdoct_app_server_protocol::ThreadListParams;
use anecdoct_app_server_protocol::ThreadListResponse;
use anecdoct_app_server_protocol::ThreadLoadedListParams;
use anecdoct_app_server_protocol::ThreadLoadedListResponse;
use anecdoct_app_server_protocol::ThreadMemoryModeSetParams;
use anecdoct_app_server_protocol::ThreadMemoryModeSetResponse;
use anecdoct_app_server_protocol::ThreadMetadataGitInfoUpdateParams;
use anecdoct_app_server_protocol::ThreadMetadataUpdateParams;
use anecdoct_app_server_protocol::ThreadMetadataUpdateResponse;
use anecdoct_app_server_protocol::ThreadNameUpdatedNotification;
use anecdoct_app_server_protocol::ThreadReadParams;
use anecdoct_app_server_protocol::ThreadReadResponse;
use anecdoct_app_server_protocol::ThreadRealtimeAppendAudioParams;
use anecdoct_app_server_protocol::ThreadRealtimeAppendAudioResponse;
use anecdoct_app_server_protocol::ThreadRealtimeAppendTextParams;
use anecdoct_app_server_protocol::ThreadRealtimeAppendTextResponse;
use anecdoct_app_server_protocol::ThreadRealtimeListVoicesResponse;
use anecdoct_app_server_protocol::ThreadRealtimeStartParams;
use anecdoct_app_server_protocol::ThreadRealtimeStartResponse;
use anecdoct_app_server_protocol::ThreadRealtimeStartTransport;
use anecdoct_app_server_protocol::ThreadRealtimeStopParams;
use anecdoct_app_server_protocol::ThreadRealtimeStopResponse;
use anecdoct_app_server_protocol::ThreadResumeParams;
use anecdoct_app_server_protocol::ThreadResumeResponse;
use anecdoct_app_server_protocol::ThreadRollbackParams;
use anecdoct_app_server_protocol::ThreadSetNameParams;
use anecdoct_app_server_protocol::ThreadSetNameResponse;
use anecdoct_app_server_protocol::ThreadShellCommandParams;
use anecdoct_app_server_protocol::ThreadShellCommandResponse;
use anecdoct_app_server_protocol::ThreadSortKey;
use anecdoct_app_server_protocol::ThreadSourceKind;
use anecdoct_app_server_protocol::ThreadStartParams;
use anecdoct_app_server_protocol::ThreadStartResponse;
use anecdoct_app_server_protocol::ThreadStartedNotification;
use anecdoct_app_server_protocol::ThreadStatus;
use anecdoct_app_server_protocol::ThreadTurnsItemsListParams;
use anecdoct_app_server_protocol::ThreadTurnsListParams;
use anecdoct_app_server_protocol::ThreadTurnsListResponse;
use anecdoct_app_server_protocol::ThreadUnarchiveParams;
use anecdoct_app_server_protocol::ThreadUnarchiveResponse;
use anecdoct_app_server_protocol::ThreadUnarchivedNotification;
use anecdoct_app_server_protocol::ThreadUnsubscribeParams;
use anecdoct_app_server_protocol::ThreadUnsubscribeResponse;
use anecdoct_app_server_protocol::ThreadUnsubscribeStatus;
use anecdoct_app_server_protocol::Turn;
use anecdoct_app_server_protocol::TurnEnvironmentParams;
use anecdoct_app_server_protocol::TurnError;
use anecdoct_app_server_protocol::TurnInterruptParams;
use anecdoct_app_server_protocol::TurnInterruptResponse;
use anecdoct_app_server_protocol::TurnItemsView;
use anecdoct_app_server_protocol::TurnStartParams;
use anecdoct_app_server_protocol::TurnStartResponse;
use anecdoct_app_server_protocol::TurnStatus;
use anecdoct_app_server_protocol::TurnSteerParams;
use anecdoct_app_server_protocol::TurnSteerResponse;
use anecdoct_app_server_protocol::UserInput as V2UserInput;
use anecdoct_app_server_protocol::WindowsSandboxReadiness;
use anecdoct_app_server_protocol::WindowsSandboxReadinessResponse;
use anecdoct_app_server_protocol::WindowsSandboxSetupCompletedNotification;
use anecdoct_app_server_protocol::WindowsSandboxSetupMode;
use anecdoct_app_server_protocol::WindowsSandboxSetupStartParams;
use anecdoct_app_server_protocol::WindowsSandboxSetupStartResponse;
use anecdoct_arg0::Arg0DispatchPaths;
use anecdoct_backend_client::AddCreditsNudgeCreditType as BackendAddCreditsNudgeCreditType;
use anecdoct_backend_client::Client as BackendClient;
use anecdoct_chatgpt::connectors;
use anecdoct_chatgpt::workspace_settings;
use anecdoct_config::CloudRequirementsLoadError;
use anecdoct_config::CloudRequirementsLoadErrorCode;
use anecdoct_config::ConfigLayerStack;
use anecdoct_config::loader::project_trust_key;
use anecdoct_config::types::McpServerTransportConfig;
use anecdoct_core::AnecdoctThread;
use anecdoct_core::AnecdoctThreadTurnContextOverrides;
use anecdoct_core::ExternalGoalPreviousStatus;
use anecdoct_core::ExternalGoalSet;
use anecdoct_core::ForkSnapshot;
use anecdoct_core::NewThread;
#[cfg(test)]
use anecdoct_core::SessionMeta;
use anecdoct_core::StartThreadOptions;
use anecdoct_core::SteerInputError;
use anecdoct_core::ThreadConfigSnapshot;
use anecdoct_core::ThreadManager;
use anecdoct_core::config::Config;
use anecdoct_core::config::ConfigOverrides;
use anecdoct_core::config::NetworkProxyAuditMetadata;
use anecdoct_core::config::edit::ConfigEdit;
use anecdoct_core::config::edit::ConfigEditsBuilder;
use anecdoct_core::exec::ExecCapturePolicy;
use anecdoct_core::exec::ExecExpiration;
use anecdoct_core::exec::ExecParams;
use anecdoct_core::exec_env::create_env;
use anecdoct_core::path_utils;
#[cfg(test)]
use anecdoct_core::read_head_for_summary;
use anecdoct_core::sandboxing::SandboxPermissions;
use anecdoct_core::windows_sandbox::WindowsSandboxLevelExt;
use anecdoct_core::windows_sandbox::WindowsSandboxSetupMode as CoreWindowsSandboxSetupMode;
use anecdoct_core::windows_sandbox::WindowsSandboxSetupRequest;
use anecdoct_core::windows_sandbox::sandbox_setup_is_complete;
use anecdoct_core_plugins::LAMBOGENIUS_CURATED_MARKETPLACE_NAME;
use anecdoct_core_plugins::PluginInstallError as CorePluginInstallError;
use anecdoct_core_plugins::PluginInstallRequest;
use anecdoct_core_plugins::PluginLoadOutcome;
use anecdoct_core_plugins::PluginReadRequest;
use anecdoct_core_plugins::PluginUninstallError as CorePluginUninstallError;
use anecdoct_core_plugins::loader::load_plugin_apps;
use anecdoct_core_plugins::loader::load_plugin_mcp_servers;
use anecdoct_core_plugins::loader::plugin_telemetry_metadata_from_root;
use anecdoct_core_plugins::manifest::PluginManifestInterface;
use anecdoct_core_plugins::marketplace::MarketplaceError;
use anecdoct_core_plugins::marketplace::MarketplacePluginSource;
use anecdoct_core_plugins::marketplace_add::MarketplaceAddError;
use anecdoct_core_plugins::marketplace_add::MarketplaceAddRequest;
use anecdoct_core_plugins::marketplace_add::add_marketplace as add_marketplace_to_anecdoct_home;
use anecdoct_core_plugins::marketplace_remove::MarketplaceRemoveError;
use anecdoct_core_plugins::marketplace_remove::MarketplaceRemoveRequest as CoreMarketplaceRemoveRequest;
use anecdoct_core_plugins::marketplace_remove::remove_marketplace;
use anecdoct_core_plugins::remote::RemoteMarketplace;
use anecdoct_core_plugins::remote::RemoteMarketplaceSource;
use anecdoct_core_plugins::remote::RemotePluginCatalogError;
use anecdoct_core_plugins::remote::RemotePluginDetail as RemoteCatalogPluginDetail;
use anecdoct_core_plugins::remote::RemotePluginServiceConfig;
use anecdoct_core_plugins::remote::RemotePluginShareContext as RemoteCatalogPluginShareContext;
use anecdoct_core_plugins::remote::RemotePluginShareSummary as RemoteCatalogPluginShareSummary;
use anecdoct_core_plugins::remote::RemotePluginSummary as RemoteCatalogPluginSummary;
use anecdoct_exec_server::EnvironmentManager;
use anecdoct_exec_server::LOCAL_FS;
use anecdoct_features::FEATURES;
use anecdoct_features::Feature;
use anecdoct_features::Stage;
use anecdoct_feedback::AnecdoctFeedback;
use anecdoct_feedback::FeedbackAttachmentPath;
use anecdoct_feedback::FeedbackUploadOptions;
use anecdoct_git_utils::git_diff_to_remote;
use anecdoct_git_utils::resolve_root_git_project_for_trust;
use anecdoct_login::AnecdoctAuth;
use anecdoct_login::AuthManager;
use anecdoct_login::CLIENT_ID;
use anecdoct_login::ServerOptions as LoginServerOptions;
use anecdoct_login::ShutdownHandle;
use anecdoct_login::auth::login_with_chatgpt_auth_tokens;
use anecdoct_login::complete_device_code_login;
use anecdoct_login::login_with_api_key;
use anecdoct_login::request_device_code;
use anecdoct_login::run_login_server;
use anecdoct_mcp::McpRuntimeEnvironment;
use anecdoct_mcp::McpServerStatusSnapshot;
use anecdoct_mcp::McpSnapshotDetail;
use anecdoct_mcp::collect_mcp_server_status_snapshot_with_detail;
use anecdoct_mcp::discover_supported_scopes;
use anecdoct_mcp::effective_mcp_servers;
use anecdoct_mcp::read_mcp_resource as read_mcp_resource_without_thread;
use anecdoct_mcp::resolve_oauth_scopes;
use anecdoct_memories_write::clear_memory_roots_contents;
use anecdoct_model_provider::ProviderAccountError;
use anecdoct_model_provider::create_model_provider;
use anecdoct_models_manager::collaboration_mode_presets::builtin_collaboration_mode_presets;
use anecdoct_protocol::ThreadId;
use anecdoct_protocol::config_types::CollaborationMode;
use anecdoct_protocol::config_types::ForcedLoginMethod;
use anecdoct_protocol::config_types::Personality;
use anecdoct_protocol::config_types::TrustLevel;
use anecdoct_protocol::config_types::WindowsSandboxLevel;
use anecdoct_protocol::dynamic_tools::DynamicToolSpec as CoreDynamicToolSpec;
use anecdoct_protocol::error::AnecdoctErr;
use anecdoct_protocol::error::Result as AnecdoctResult;
#[cfg(test)]
use anecdoct_protocol::items::TurnItem;
use anecdoct_protocol::models::ResponseItem;
#[cfg(test)]
use anecdoct_protocol::permissions::FileSystemSandboxPolicy;
use anecdoct_protocol::protocol::AgentStatus;
use anecdoct_protocol::protocol::ConversationAudioParams;
use anecdoct_protocol::protocol::ConversationStartParams;
use anecdoct_protocol::protocol::ConversationStartTransport;
use anecdoct_protocol::protocol::ConversationTextParams;
use anecdoct_protocol::protocol::EventMsg;
#[cfg(test)]
use anecdoct_protocol::protocol::GitInfo as CoreGitInfo;
use anecdoct_protocol::protocol::InitialHistory;
use anecdoct_protocol::protocol::McpAuthStatus as CoreMcpAuthStatus;
use anecdoct_protocol::protocol::Op;
use anecdoct_protocol::protocol::RateLimitSnapshot as CoreRateLimitSnapshot;
use anecdoct_protocol::protocol::RealtimeVoicesList;
use anecdoct_protocol::protocol::ResumedHistory;
use anecdoct_protocol::protocol::ReviewDelivery as CoreReviewDelivery;
use anecdoct_protocol::protocol::ReviewRequest;
use anecdoct_protocol::protocol::ReviewTarget as CoreReviewTarget;
use anecdoct_protocol::protocol::RolloutItem;
use anecdoct_protocol::protocol::SessionConfiguredEvent;
#[cfg(test)]
use anecdoct_protocol::protocol::SessionMetaLine;
use anecdoct_protocol::protocol::TurnEnvironmentSelection;
use anecdoct_protocol::protocol::USER_MESSAGE_BEGIN;
use anecdoct_protocol::protocol::W3cTraceContext;
use anecdoct_protocol::user_input::MAX_USER_INPUT_TEXT_CHARS;
use anecdoct_protocol::user_input::UserInput as CoreInputItem;
use anecdoct_rmcp_client::perform_oauth_login_return_url;
use anecdoct_rollout::EventPersistenceMode;
use anecdoct_rollout::is_persisted_rollout_item;
use anecdoct_rollout::state_db::StateDbHandle;
use anecdoct_rollout::state_db::reconcile_rollout;
use anecdoct_state::ThreadMetadata;
use anecdoct_state::log_db::LogDbLayer;
use anecdoct_thread_store::ArchiveThreadParams as StoreArchiveThreadParams;
use anecdoct_thread_store::GitInfoPatch as StoreGitInfoPatch;
use anecdoct_thread_store::ListThreadsParams as StoreListThreadsParams;
use anecdoct_thread_store::LocalThreadStore;
use anecdoct_thread_store::ReadThreadByRolloutPathParams as StoreReadThreadByRolloutPathParams;
use anecdoct_thread_store::ReadThreadParams as StoreReadThreadParams;
use anecdoct_thread_store::SortDirection as StoreSortDirection;
use anecdoct_thread_store::StoredThread;
use anecdoct_thread_store::ThreadMetadataPatch as StoreThreadMetadataPatch;
use anecdoct_thread_store::ThreadSortKey as StoreThreadSortKey;
use anecdoct_thread_store::ThreadStore;
use anecdoct_thread_store::ThreadStoreError;
use anecdoct_utils_absolute_path::AbsolutePathBuf;
use anecdoct_utils_pty::DEFAULT_OUTPUT_BYTES_CAP;
use chrono::Duration as ChronoDuration;
use chrono::SecondsFormat;
use std::collections::HashMap;
use std::collections::HashSet;
use std::io::Error as IoError;
use std::path::Path;
use std::path::PathBuf;
use std::result::Result;
use std::sync::Arc;
use std::time::Duration;
use std::time::Instant;
use tokio::sync::Mutex;
use tokio::sync::Semaphore;
use tokio::sync::SemaphorePermit;
use tokio::sync::broadcast;
use tokio::sync::oneshot;
use tokio::sync::watch;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use toml::Value as TomlValue;
use tracing::Instrument;
use tracing::error;
use tracing::info;
use tracing::warn;
use uuid::Uuid;

#[cfg(test)]
use anecdoct_app_server_protocol::ServerRequest;

mod account_processor;
mod apps_processor;
mod catalog_processor;
mod command_exec_processor;
mod config_processor;
mod environment_processor;
mod external_agent_config_processor;
mod feedback_doctor_report;
mod feedback_processor;
mod fs_processor;
mod git_processor;
mod initialize_processor;
mod marketplace_processor;
mod mcp_processor;
mod plugins;
mod process_exec_processor;
mod remote_control_processor;
mod search;
mod thread_processor;
mod token_usage_replay;
mod turn_processor;
mod windows_sandbox_processor;

pub(crate) use account_processor::AccountRequestProcessor;
pub(crate) use apps_processor::AppsRequestProcessor;
pub(crate) use catalog_processor::CatalogRequestProcessor;
pub(crate) use command_exec_processor::CommandExecRequestProcessor;
pub(crate) use config_processor::ConfigRequestProcessor;
pub(crate) use environment_processor::EnvironmentRequestProcessor;
pub(crate) use external_agent_config_processor::ExternalAgentConfigRequestProcessor;
pub(crate) use feedback_processor::FeedbackRequestProcessor;
pub(crate) use fs_processor::FsRequestProcessor;
pub(crate) use git_processor::GitRequestProcessor;
pub(crate) use initialize_processor::InitializeRequestProcessor;
pub(crate) use marketplace_processor::MarketplaceRequestProcessor;
pub(crate) use mcp_processor::McpRequestProcessor;
pub(crate) use plugins::PluginRequestProcessor;
pub(crate) use process_exec_processor::ProcessExecRequestProcessor;
pub(crate) use remote_control_processor::RemoteControlRequestProcessor;
pub(crate) use search::SearchRequestProcessor;
pub(crate) use thread_goal_processor::ThreadGoalRequestProcessor;
pub(crate) use thread_processor::ThreadRequestProcessor;
pub(crate) use turn_processor::TurnRequestProcessor;
pub(crate) use windows_sandbox_processor::WindowsSandboxRequestProcessor;

use crate::error_code::internal_error;
use crate::error_code::invalid_request;
use crate::filters::compute_source_filters;
use crate::filters::source_kind_matches;
use crate::thread_state::ConnectionCapabilities;
use crate::thread_state::ThreadListenerCommand;
use crate::thread_state::ThreadState;
use crate::thread_state::ThreadStateManager;
use token_usage_replay::latest_token_usage_turn_id_from_rollout_items;
use token_usage_replay::send_thread_token_usage_update_to_connection;

mod config_errors;
mod request_errors;
mod thread_goal_processor;
mod thread_lifecycle;
mod thread_resume_redaction;
mod thread_summary;

use self::config_errors::*;
use self::request_errors::*;
use self::thread_goal_processor::api_thread_goal_from_state;
use self::thread_lifecycle::*;
use self::thread_resume_redaction::*;
use self::thread_summary::*;

pub(crate) use self::thread_lifecycle::populate_thread_turns_from_history;
pub(crate) use self::thread_processor::thread_from_stored_thread;
#[cfg(test)]
pub(crate) use self::thread_summary::read_summary_from_rollout;
#[cfg(test)]
pub(crate) use self::thread_summary::summary_to_thread;

pub(crate) fn build_api_turns_from_rollout_items(items: &[RolloutItem]) -> Vec<Turn> {
    let mut builder = ThreadHistoryBuilder::new();
    for item in items {
        if is_persisted_rollout_item(item, EventPersistenceMode::Limited) {
            builder.handle_rollout_item(item);
        }
    }
    builder.finish()
}
